- hosts: all
  tasks:
   - name: install remote apt deps
     apt:
       name: ['apt-transport-https', 'ca-certificates', 'gnupg2', 'software-properties-common', 'arptables', 'curl']
       state: present

   - name: remove  Docker from Debian repository
     apt:
       name: docker.io
       state: absent

   - name: remove k8s node
     apt:
       name: kubernetes-node
       state: absent
       force: yes

   - name: remove k8s client
     apt:
       name: kubernetes-client
       state: absent
       update_cache: true

   - name: remove nftables
     apt:
       name: nftables
       state: absent
       update_cache: true

- hosts: master
  become: yes
  tasks:
   - name: install k8s cluster
     apt:
       name: kubernetes-master
       state: absent
