- hosts: all
  tasks:
   - name: install remote apt deps
     apt:
       name: "{{ item }}"
       state: present
     with_items:
       - apt-transport-https
       - ca-certificates
       - gnupg2
       - software-properties-common

   - name: install Docker
     apt:
       name: docker.io
       state: absent

   - name: install k8s node
     apt:
       name: kubernetes-node
       state: absent
       force: yes

   - name: install k8s client
     apt:
       name: kubernetes-client
       state: absent
       update_cache: true


- hosts: master
  become: yes
  tasks:
   - name: install k8s cluster
     apt:
       name: kubernetes-master
       state: absent
