- hosts: all
  tasks:
   - name: install remote apt deps
     apt:
       name: ['apt-transport-https', 'ca-certificates', 'gnupg2', 'software-properties-common', 'arptables', 'curl', 'ebtables']
       state: present

   - name: remove nftables
     apt:
       name: nftables
       state: absent
       update_cache: true

