- hosts: master
  become: yes
  tasks:
   - name: add helm  apt-key
     apt_key:
       url: https://baltocdn.com/helm/signing.asc
       state: present

   - name: add Helm APT repository
     apt_repository:
      repo: deb https://baltocdn.com/helm/stable/debian/ all main
      state: present
      filename: 'helm'

   - name: install helm
     apt:
       name: helm
       state: present

